# Generated by Django 3.1.1 on 2020-09-16 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelform', '0003_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=50)),
            ],
        ),
    ]
