# Generated by Django 3.1.1 on 2020-09-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelform', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'My_Product',
            },
        ),
    ]
